[package]
name = "SuiTears"
version = "0.0.1"
published-at = "0x901b511b878f90f1b833df46648224b913df60f8b3165086caba6f59e75d6e98"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "framework/testnet" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
suitears = "0x901b511b878f90f1b833df46648224b913df60f8b3165086caba6f59e75d6e98"
std = "0x1"
sui = "0x2"